core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-checkout-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-2.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-subscription.html

We are supporting a new design for the `variant-select` formatter that will replace the dropdowns with selectable boxes. Users will be able to switch between these with a site-level tweak so we need the markup for both.

[COM-11786] Add markup for new variant select layout

---

core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-checkout-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-2.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-subscription.html

This PR adds the `data-variant-option-name` attribute to the `variant-radiobtn-wrapper` for parity with the preceding <select> elements. It also wraps all calls to name in htmltag formatters to escape any special characters e.g. <, >.

Add data-variant-option-name attribute to radio button wrapper for parity

---

core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-checkout-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-2.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-subscription.html

This PR adds an `aria-label` property to the select element to expose its purpose to screenreaders.

Add aria labels to variant select for accessibility

---

core/src/main/resources/com/squarespace/template/plugins/platform/product-price.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-3.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-6.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-finite-subscription-on-sale-bi-monthly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-finite-subscription-on-sale-bi-weekly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-finite-subscription-on-sale-monthly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-finite-subscription-on-sale-weekly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-subscription-on-sale-bi-monthly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-subscription-on-sale-bi-weekly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-subscription-on-sale-monthly.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-price-subscription-on-sale-weekly.html

For more context on the changes, see comments thread in the ticket: https://jira.squarespace.net/browse/COM-10948
or https://a11yproject.com/posts/how-to-hide-content/
There is no visible change as part of the changes, this change is to assist those users who rely on screen readers.

COM-10948: Add hidden span for screen reader to read out label for sale price/original price

---

core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-checkout-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-2.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-subscription.html

This PR adds the markup to render an alternate layout for the variant-select formatter. To avoid this markup displaying on sites, we are running a global CSS invalidation with new style rules to hide this markup by default.

Add radio button layout to variants-select formatter

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-src-set-1.html

This is in relation to Zach Gawlik's PR here: https://github.com/Squarespace/template-engine/pull/3/files
Currently, the JSON-T compiler outputs `data-srcset="..."`
This PR changes the compiler to output with srcset and not the data-attribute so that ImageLoader JS does not need to run and set the srcset attribute,

[CMS-38076] - update template compiler to output srcset instead of data-srcset

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/test/java/com/squarespace/template/plugins/platform/ContentFormattersTest.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-5.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-6.html

when determining alt-text for an image on a contentItem, we fallback to the contentItem.body field if the title is missing. This is documented behavior in the [KB](**url**). However, if the body field is very long (e.g. in the case of a blog post), it results in slow loading issues that we have been observing on the platform. 
This PR truncates the body field to < 1000 characters, after any HTML tags have been removed. 
**Verifications:**
1. Added tests to verify that item body is used and truncated
2. test on local site-server

[CMS-39266] Truncate content item body if longer than 1000 characters when determining alt-text

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-src-set-1.html

This covers a case such as:
- User uploads image 215px wide
- Browser is rendering 400px
- We only generate 100w because we don't scale up to next size (300w)
- Browser ends up request 100w instead of original
By outputting all the sizes that we have generated and finally the originally, we serve the highest available size that we have in the above case.

Output the original format with no size declared

---

core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html

This PR adds the html formatter to the product variant option titles for sanitization. The only real change is changing this line ` <div class="variant-option-title">{name}: </div>` to `<div class="variant-option-title">{name|htmltag}: </div>`. The rest is cleaning up where the loops start and end, as well as the indentations within it to be more readable.

[VULN-414] Sanitize product option title

---

core/src/main/java/com/squarespace/template/plugins/platform/CommerceFormatters.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-status-9.html

This PR adds HTML escaping when outputting the custom out of stock message for products and updates the test case. I'm using `PluginUtils.escapeHtmlAttribute` to do the escaping, which is used by the `htmltag` and `htmlattr` formatters.
VULN-329

VULN-329: Escape custom out of stock messages

---

core/src/main/resources/com/squarespace/template/plugins/platform/quantity-input.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-quantity-input-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-quantity-input-4.html

On the products detail page, the Quantity label is linked with the input visually, but not semantically. A screen reader user landing on this input will not know that it's a quantity input.
The change makes it so that the are semantically linked.
There will be follow-up PRs for style changes in new-bedford and v6 (those changes will be backwards-compatible, so those will go in first).
EDIT: I updated this PR so that style changes won't be required. So no additional changes will be necessary beyond just the ones in this PR.
Ticket: https://jira.squarespace.net/browse/COM-9030

Products - Quantity input doesn't have a label

---

core/src/main/java/com/squarespace/template/Constants.java
core/src/main/java/com/squarespace/template/plugins/platform/CommerceFormatters.java
core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-4.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-5.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-6.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-7.html
core/src/test/resources/com/squarespace/template/plugins/platform/get-item-variant-options.json

Adds a method to `CommerceFormatters.java` that translates the "Value" string displayed when a product is a gift card and defaults to the user input variant name otherwise.
Currently there is a bug where the text above the gift card option drop-down displayed "Value" in English in all languages. This formatting method solves this bug.
* Added a method to `CommerceFormatters.java` that resolves the `displayName` based on the locale if a product is a gift card type otherwise it returns the `name` of the variant
* Changed the `variant-option-title` tag within `variants-select.html` to `{displayName}` with a default to `name` for non-gift card product types.
This change also required adding the string `Value` to the `products-en-US.json` and `products-2.0-en-US.json` files within site-server …

I18NPROD-322-add-method-to-format-value-for-gift-card

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/main/java/com/squarespace/template/plugins/platform/enums/BlockType.java
core/src/test/java/com/squarespace/template/plugins/platform/ContentFormattersTest.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-3.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-7.html

[Ticket](https://jira.squarespace.net/browse/CMS-33803)
This is a fixed version of [an earlier PR](https://github.com/Squarespace/template-compiler/pull/18). There was a migration that populated the `altText` field on all `ContentItems` associated with Image Blocks. That PR was intended to read that value instead of computing the `altText` from other data, like the title and filename. The issue was that other types of images, like product images, didn't have this field populated during the migration and were rendered without any alt text. ~This time, I left the old logic as a fallback if the item has no alt text.~
The `blockType` is now being checked so that only image blocks are impacted by this change. This requires a change to the `ImageWidget` in site-server ([PR …

[CMS-33803] Use alt text field on contentItems

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/test/java/com/squarespace/template/plugins/platform/ContentFormattersTest.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-src-set-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-image-src-set-3.html

We are currently adding orignal image candidate to srcset without width descriptor. This PR adds the next Squarespace image size width descriptor to srcset's original image candidate and avoid adding original image candidate if 2500w is already set because 2500w is already the biggest size we support (it is probably same image as orginal too). 
According to scrset spec https://html.spec.whatwg.org/multipage/images.html#image-candidate-string, srcset attribute for original image format should have width descriptor for our case.
> If an image candidate string for an element has the width descriptor specified, all other image candidate strings for that element must also have the width descriptor specified.
> If an element has a sizes attribute present, all image candidate strings for that …

PERF-2091: Ensure all srcset image candidate has width descriptor

---

core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-5.html

This PR escapes custom option names in the variant select formatter to prevent potential XSS attacks.
VULN ticket: https://squarespace.atlassian.net/browse/VULN-414

VULN-414: Escape custom option names

---

core/src/main/java/com/squarespace/template/Constants.java
core/src/test/java/com/squarespace/template/plugins/platform/i18n/MoneyFormatterTest.java

This is a follow up to an [outstanding pr](https://github.com/sqsp/squarespace-v6/pull/24785) where we pass `featureFlags.useCLDRMoneyFormat` into template compiler. The work included here is updating `CLDR_MONEYFORMAT_KEY` to check under `featureFlags` (open to naming suggestions) instead of `website`.
Placing `useCLDRMoneyFormat` under `website` has unintended consequences in certain situations. Mainly when template code checks the presence of `website` to determine rendering paths. This specifically became an issue when rendering the [form.block](https://github.com/sqsp/squarespace-v6/blob/master/site-server/src/main/webapp/templates-v6/system/blocks/form.block#L164-L178). This caused an additional form field to render since `useCLDRMoneyFormat` needed to exist in `website`.
I decided …

I18NPROD-1685 - Update the useCLDRMoneyFormat flag check

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/test/java/com/squarespace/template/plugins/platform/ContentFormattersTest.java

currently, the lightness and saturation values of the HSLA model are stored as a decimal value between 0-1.  however, CSS needs these values as a percentage (0-100).  this formatter takes in an HSLA model from `{ "hue": 360, "saturation": 1, "lightness": 1, "alpha": 0.5 })` and outputs `hsla(360, 100%, 100%, 0.5)`
to test this, i had the following code in a JSON-T file:
```
** without formatter: {customColor.values.hue}, {customColor.values.saturation}, {customColor.values.lightness}, {customColor.values.alpha};
** with formatter: {customColor.values|hslaColor};
```
it outputted the following:
UPDATE:
here is a screenshot that shows the formatter handling HSL vs. HSLA.
here is a screenshot of an error message for an HSLA that has all out of bounds values:

[CMS-45395] - add HSLA Color formatter

---

core/src/main/java/com/squarespace/template/plugins/platform/ContentFormatters.java
core/src/test/java/com/squarespace/template/plugins/platform/ContentFormattersTest.java

the website-color formatter originally rounded values to one decimal point. this PR updates it to two decimal points.

[CMS-45394] - update website-color formatter to round to nearest two decimal points

---

core/src/main/resources/com/squarespace/template/plugins/platform/variants-select.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-product-checkout-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-1.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-2.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-4.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-5.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-6.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-7.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-variants-select-subscription.html

This change is because radio buttons styles are being changed to a button. We also want to apply secondary button styles to radio buttons on the PDP page. See screen shot below:

[COM-26547]: added secondary button class to radio label, role as button and tabIndex

---

core/src/main/java/com/squarespace/template/GeneralUtils.java
core/src/main/java/com/squarespace/template/plugins/CoreFormatters.java
core/src/test/java/com/squarespace/template/GeneralUtilsTest.java
core/src/test/java/com/squarespace/template/UnitTestBase.java
core/src/test/java/com/squarespace/template/plugins/CoreFormattersTest.java
core/src/test/resources/com/squarespace/template/plugins/f-key-by-1.html

https://github.com/Squarespace/template-engine/pull/21
- Added new key-by formatter which takes a given array node and tries to map each of the objects inside by the value at the given key path. This can be stored in a var and used in conjunction with the get or prop formatters to allow the user to easily access objects by some key (e.g. id) from anywhere in the template
- Added new method, getNodeAtPath, to GeneralUtils with code taken from the prop formatter because the same logic is used by key-by
- Updated the prop formatter to use the new util
- Added tests for new key-by formatter and getNodeAtPath

[DIG-641] key-by formatter

---

core/src/main/resources/com/squarespace/template/plugins/platform/product-scarcity.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-scarcity-default-hidden.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-scarcity-default-shown-and-variants.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-scarcity-default-shown-escape-html.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-scarcity-default-shown.html

When attributes exists, we want to hide `product-scarcity` When on the PLP there's a edge case where product-status limit is for example, 10. When a product has multiple variants, the summation of variants (TOTAL_STOCK) could be above 10. However, each variant could be below 10. In this case, we're actually showing TOTAL_STOCK as one of the variants.. which is not right. Since for total stock scarcity, `attributes` is not part of the object, we can assume that scarcity with attributes are a variant while without are total stock.

[COM-28756]: update product-scarcity to hide when attributes exists

---

core/src/main/java/com/squarespace/template/plugins/platform/CommerceFormatters.java
core/src/main/resources/com/squarespace/template/plugins/platform/subscription-price.html
core/src/test/java/com/squarespace/template/plugins/platform/CommerceFormattersTest.java
core/src/test/resources/com/squarespace/template/plugins/platform/f-subscription-price-multiple-variants-and-multiple-pricing-options.html
core/src/test/resources/com/squarespace/template/plugins/platform/f-subscription-price-variants-with-same-pricing.html

This PR fixes one case where instead of just checking if product has variants to calculate the `from {price}` we need to calculate if prices actually differ in between variants. this is because I missed the case where there could be multiple variants but all with the same price. In this case, we would show the price and not the `from {price}`

[COM-32536]: Variant pricing bug fixes
